[package]
name = "renamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.27"
regex = "1.5.6"
tui = "0.18"
crossterm = "0.23"
itertools = "0.10.3"